language: node_js
node_js:
  - 8.9.3

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm test
  - bin/deploy_prod_backend.sh --dry-run

deploy:
  - provider: script
    skip_cleanup: true
    script: bin/deploy_prod_backend.sh --actually-deploy-graphcool
    on:
      branch: master
